// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "เช็คว่า service พร้อมทำงาน",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.HealthResponse"
                        }
                    }
                }
            }
        },
        "/test-send": {
            "post": {
                "description": "ยิง SMS จริงผ่าน easymoney adapter (ยังไม่ผ่าน DB/queue) — คืน message_id ที่ provider ตอบกลับ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "ทดสอบส่ง SMS ผ่าน easymoney",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.TestSendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.TestSendResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.ErrorType": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-comments": {
                "ErrorPermanent": "เบอร์ผิด/token invalid -\u003e ไม่ต้อง retry",
                "ErrorTemporary": "network/timeout/rate limit -\u003e retry"
            },
            "x-enum-descriptions": [
                "network/timeout/rate limit -\u003e retry",
                "เบอร์ผิด/token invalid -\u003e ไม่ต้อง retry"
            ],
            "x-enum-varnames": [
                "ErrorTemporary",
                "ErrorPermanent"
            ]
        },
        "domain.Result": {
            "type": "object",
            "properties": {
                "err": {
                    "description": "nil = สำเร็จ",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.SendError"
                        }
                    ]
                },
                "notificationID": {
                    "type": "string"
                },
                "providerMessageID": {
                    "description": "id ที่ provider คืนมา (เก็บไว้ map DLR)",
                    "type": "string"
                }
            }
        },
        "domain.SendError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/domain.ErrorType"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handler.HealthResponse": {
            "type": "object",
            "properties": {
                "env": {
                    "type": "string",
                    "example": "local"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "handler.TestSendRequest": {
            "type": "object",
            "required": [
                "message",
                "numbers"
            ],
            "properties": {
                "message": {
                    "description": "เนื้อความ",
                    "type": "string",
                    "example": "ทดสอบ sms"
                },
                "numbers": {
                    "description": "เบอร์ปลายทาง",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "0806906003"
                    ]
                },
                "source": {
                    "description": "ว่างได้ = ใช้ค่าจาก config",
                    "type": "string",
                    "example": "easymoney"
                }
            }
        },
        "handler.TestSendResponse": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string",
                    "example": "sms"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Result"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Service Notification API",
	Description:      "API สำหรับส่ง SMS / FCM / Email notification (RabbitMQ + Azure SQL)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
